<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <StartupObject>Sub Main</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsForms</MyType>
    <OptionStrict>On</OptionStrict>
    <ImportedNamespaces>Microsoft.Data.SqlClient=False,MQTTnet=False,Renci.SshNet=False,System.Data=False,System.Drawing=False,System.Windows.Forms=False,Microsoft.VisualBasic=True,System=True,System.Collections=True,System.Collections.Generic=True,System.Diagnostics=True,System.Linq=True,System.Xml.Linq=True,System.Threading.Tasks=True,Optolink_02=True</ImportedNamespaces>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Documentation\Export_20251027_165410.xml" />
  </ItemGroup>

  <ItemGroup>
    <Import Include="Microsoft.Data.SqlClient" />
    <Import Include="MQTTnet" />
    <Import Include="Renci.SshNet" />
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
    <PackageReference Include="MQTTnet" Version="4.3.7.1207" />
    <PackageReference Include="SSH.NET" Version="2025.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="My Project\Application.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
    <None Update="XML\ecnDataPointType.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Datenbank\ecnViessmann.mdf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Datenbank\" />
    <Folder Include="PY-Quellcode\InsideViessmannVitosoft\" />
    <Folder Include="XML\" />
    <Folder Include="Parsers\" />
  </ItemGroup>

</Project>